"""empty message

Revision ID: 1c63f30d0ef8
Revises: 4873ece93a13
Create Date: 2015-11-19 16:19:20.054661

"""

# revision identifiers, used by Alembic.
revision = '1c63f30d0ef8'
down_revision = '4873ece93a13'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('can_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['can_id'], ['book_can.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    ### end Alembic commands ###
