"""empty message

Revision ID: 313976af8589
Revises: 1ef87e10f6c0
Create Date: 2015-11-21 17:46:22.157705

"""

# revision identifiers, used by Alembic.
revision = '313976af8589'
down_revision = '1ef87e10f6c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('latest_ip', sa.String(length=15), nullable=True))
    op.add_column('user', sa.Column('latest_login', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'latest_login')
    op.drop_column('user', 'latest_ip')
    ### end Alembic commands ###
