"""empty message

Revision ID: 4873ece93a13
Revises: None
Create Date: 2015-11-19 16:17:45.712994

"""

# revision identifiers, used by Alembic.
revision = '4873ece93a13'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_can',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('intro', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('passwd', sa.Text(), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('intro', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('can_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['can_id'], ['book_can.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discuss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('can_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['can_id'], ['book_can.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discuss')
    op.drop_table('book')
    op.drop_table('user')
    op.drop_table('book_can')
    ### end Alembic commands ###
