"""empty message

Revision ID: 4bcd52a89c67
Revises: 1c63f30d0ef8
Create Date: 2015-11-20 12:13:21.918107

"""

# revision identifiers, used by Alembic.
revision = '4bcd52a89c67'
down_revision = '1c63f30d0ef8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'book_can', sa.Column('time', sa.DateTime(), nullable=True))
    op.add_column(u'book_can', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book_can', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_can', type_='foreignkey')
    op.drop_column(u'book_can', 'user_id')
    op.drop_column(u'book_can', 'time')
    op.drop_table('message_board')
    ### end Alembic commands ###
