"""empty message

Revision ID: 563acb57641f
Revises: 4bcd52a89c67
Create Date: 2015-11-21 11:21:34.443582

"""

# revision identifiers, used by Alembic.
revision = '563acb57641f'
down_revision = '4bcd52a89c67'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authentication', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=30), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    op.drop_column('user', 'authentication')
    ### end Alembic commands ###
